language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.10"

os:
  - linux
  - windows

before_install:
  cpanm -n Devel::Cover::Report::Coveralls

script:
  perl Makefile.PL && make test RELEASE_TESTING=1 POD_COVERAGE_TESTING=1 && cover -test -report coveralls